//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Ifyvami
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип ТП.
    /// </summary>
    // *** Start programmer edit section *** (типТП CustomAttributes)

    // *** End programmer edit section *** (типТП CustomAttributes)
    [AutoAltered()]
    [Caption("Тип ТП")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("типТПE", new string[] {
            "Код as \'Код\'",
            "Тип as \'Тип\'"})]
    [View("типТПL", new string[] {
            "Код as \'Код\'",
            "Тип as \'тип\'"})]
    public class типТП : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private string fТип;
        
        // *** Start programmer edit section *** (типТП CustomMembers)

        // *** End programmer edit section *** (типТП CustomMembers)

        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (типТП.Код CustomAttributes)

        // *** End programmer edit section *** (типТП.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (типТП.Код Get start)

                // *** End programmer edit section *** (типТП.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (типТП.Код Get end)

                // *** End programmer edit section *** (типТП.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (типТП.Код Set start)

                // *** End programmer edit section *** (типТП.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (типТП.Код Set end)

                // *** End programmer edit section *** (типТП.Код Set end)
            }
        }
        
        /// <summary>
        /// Тип.
        /// </summary>
        // *** Start programmer edit section *** (типТП.Тип CustomAttributes)

        // *** End programmer edit section *** (типТП.Тип CustomAttributes)
        [StrLen(255)]
        public virtual string Тип
        {
            get
            {
                // *** Start programmer edit section *** (типТП.Тип Get start)

                // *** End programmer edit section *** (типТП.Тип Get start)
                string result = this.fТип;
                // *** Start programmer edit section *** (типТП.Тип Get end)

                // *** End programmer edit section *** (типТП.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (типТП.Тип Set start)

                // *** End programmer edit section *** (типТП.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (типТП.Тип Set end)

                // *** End programmer edit section *** (типТП.Тип Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "типТПE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View типТПE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("типТПE", typeof(IIS.Ifyvami.типТП));
                }
            }
            
            /// <summary>
            /// "типТПL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View типТПL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("типТПL", typeof(IIS.Ifyvami.типТП));
                }
            }
        }
    }
}
