//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Ifyvami
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Транспсрд.
    /// </summary>
    // *** Start programmer edit section *** (транспсрд CustomAttributes)

    // *** End programmer edit section *** (транспсрд CustomAttributes)
    [AutoAltered()]
    [Caption("Транспсрд")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("транспрдE", new string[] {
            "Код as \'Код\'",
            "Наименование as \'Наименование\'",
            "типТП as \'Типтп\'",
            "типТП.Тип as \'ТИптп\'"})]
    [View("транспсрдE", new string[] {
            "Код as \'Код\'",
            "Наименование as \'Наименование\'",
            "типТП as \'Тип ТП\'",
            "типТП.Тип as \'Тип\'"}, Hidden=new string[] {
            "типТП.Тип"})]
    [MasterViewDefineAttribute("транспсрдE", "типТП", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Тип")]
    [View("транспсрдL", new string[] {
            "Код as \'Код\'",
            "Наименование as \'Наименование\'",
            "типТП.Тип as \'Типтп\'"})]
    public class транспсрд : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private string fНаименование;
        
        private IIS.Ifyvami.типТП fтипТП;
        
        // *** Start programmer edit section *** (транспсрд CustomMembers)

        // *** End programmer edit section *** (транспсрд CustomMembers)

        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (транспсрд.Код CustomAttributes)

        // *** End programmer edit section *** (транспсрд.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (транспсрд.Код Get start)

                // *** End programmer edit section *** (транспсрд.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (транспсрд.Код Get end)

                // *** End programmer edit section *** (транспсрд.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (транспсрд.Код Set start)

                // *** End programmer edit section *** (транспсрд.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (транспсрд.Код Set end)

                // *** End programmer edit section *** (транспсрд.Код Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (транспсрд.Наименование CustomAttributes)

        // *** End programmer edit section *** (транспсрд.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (транспсрд.Наименование Get start)

                // *** End programmer edit section *** (транспсрд.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (транспсрд.Наименование Get end)

                // *** End programmer edit section *** (транспсрд.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (транспсрд.Наименование Set start)

                // *** End programmer edit section *** (транспсрд.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (транспсрд.Наименование Set end)

                // *** End programmer edit section *** (транспсрд.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Транспсрд.
        /// </summary>
        // *** Start programmer edit section *** (транспсрд.типТП CustomAttributes)

        // *** End programmer edit section *** (транспсрд.типТП CustomAttributes)
        [PropertyStorage(new string[] {
                "типТП"})]
        [NotNull()]
        public virtual IIS.Ifyvami.типТП типТП
        {
            get
            {
                // *** Start programmer edit section *** (транспсрд.типТП Get start)

                // *** End programmer edit section *** (транспсрд.типТП Get start)
                IIS.Ifyvami.типТП result = this.fтипТП;
                // *** Start programmer edit section *** (транспсрд.типТП Get end)

                // *** End programmer edit section *** (транспсрд.типТП Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (транспсрд.типТП Set start)

                // *** End programmer edit section *** (транспсрд.типТП Set start)
                this.fтипТП = value;
                // *** Start programmer edit section *** (транспсрд.типТП Set end)

                // *** End programmer edit section *** (транспсрд.типТП Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "транспрдE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View транспрдE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("транспрдE", typeof(IIS.Ifyvami.транспсрд));
                }
            }
            
            /// <summary>
            /// "транспсрдE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View транспсрдE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("транспсрдE", typeof(IIS.Ifyvami.транспсрд));
                }
            }
            
            /// <summary>
            /// "транспсрдL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View транспсрдL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("транспсрдL", typeof(IIS.Ifyvami.транспсрд));
                }
            }
        }
    }
}
